// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADR1Pb31lYY9Rf6gQWQC7wyFNsgzDX0Fg',
    appId: '1:901207354411:web:c63a498b654d049d0c4e6e',
    messagingSenderId: '901207354411',
    projectId: 'fir-project-1c32f',
    authDomain: 'fir-project-1c32f.firebaseapp.com',
    storageBucket: 'fir-project-1c32f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4VjXCVoCtfMmRBWsMnHbqqd3PzsxFrwI',
    appId: '1:901207354411:android:fef155887da7e4ce0c4e6e',
    messagingSenderId: '901207354411',
    projectId: 'fir-project-1c32f',
    storageBucket: 'fir-project-1c32f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGO_WEptfV46efebUSJKRK8YFr-vGJzOU',
    appId: '1:901207354411:ios:3b1f5dc1ab9330950c4e6e',
    messagingSenderId: '901207354411',
    projectId: 'fir-project-1c32f',
    storageBucket: 'fir-project-1c32f.firebasestorage.app',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGO_WEptfV46efebUSJKRK8YFr-vGJzOU',
    appId: '1:901207354411:ios:3b1f5dc1ab9330950c4e6e',
    messagingSenderId: '901207354411',
    projectId: 'fir-project-1c32f',
    storageBucket: 'fir-project-1c32f.firebasestorage.app',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADR1Pb31lYY9Rf6gQWQC7wyFNsgzDX0Fg',
    appId: '1:901207354411:web:458c63284e8fba210c4e6e',
    messagingSenderId: '901207354411',
    projectId: 'fir-project-1c32f',
    authDomain: 'fir-project-1c32f.firebaseapp.com',
    storageBucket: 'fir-project-1c32f.firebasestorage.app',
  );
}
